import type { EmotionState, EndingSeedName, GameState, HiddenTraitName, MemoryFragment, Relationship, ScheduleId, SeasonLabel, StatName } from './types';
const clamp = (v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const SEASONS: SeasonLabel[]=['봄','여름','가을','겨울'];
export const seasonMoodLine: Record<SeasonLabel,string> = { 봄:'창밖에는 연한 봄빛이 번지고 있습니다.', 여름:'긴 오후의 햇빛이 방 안에 머물고 있습니다.', 가을:'창밖 어딘가에서 낙엽이 조용히 떨어집니다.', 겨울:'차가운 바깥과 달리 방 안은 포근합니다.'};
const traitKeys: HiddenTraitName[]=['dreamer','explorer','creator','leader','loner','empathetic','obsessive','rebellious','stable','anxious'];
const endingKeys: EndingSeedName[]=['indieGameCreator','belovedGameDirector','natureDocumentaryMaker','quietNovelist','warmTeacher','lonelyGenius','lateBloomingOrdinaryLife','burnedOutProdigy'];
const mkTraits=()=>Object.fromEntries(traitKeys.map(k=>[k,0])) as Record<HiddenTraitName,number>; const mkEndings=()=>Object.fromEntries(endingKeys.map(k=>[k,0])) as Record<EndingSeedName,number>;
const mkRelationships=():Record<string,Relationship>=>({parents:{id:'parents',name:'엄마 아빠',type:'family',description:'동하가 세상을 안전하게 느끼게 해주는 가장 가까운 사람들.',note:'가장 가까운 품',metrics:{intimacy:0,trust:0},memories:[]},neighborhoodChild:{id:'neighborhoodChild',name:'동네 아이',type:'friend',description:'아직은 어색하지만 조금씩 익숙해지는 또래.',note:'아직은 어색한 친구',metrics:{intimacy:0},memories:[]},walkingGrandma:{id:'walkingGrandma',name:'산책길 할머니',type:'neighbor',description:'자주 마주치는 따뜻한 인사.',note:'자주 마주치는 따뜻한 사람',metrics:{intimacy:0},memories:[]},strangeDog:{id:'strangeDog',name:'낯선 강아지',type:'animal',description:'무섭지만 이상하게 시선을 빼앗는 존재.',note:'무섭지만 궁금한 존재',metrics:{curiosity:0,comfort:0},memories:[]},tinyBug:{id:'tinyBug',name:'작은 벌레',type:'nature',description:'놀랍고 이상한 작은 생명.',note:'놀랍고 이상한 작은 생명',metrics:{curiosity:0},memories:[]},heeseonSeed:{id:'heeseonSeed',name:'또렷한 눈빛의 아이',type:'seed',description:'미래에 중요한 인연이 될지도 모르는 작은 스침.',note:'아주 잠깐 스친 기억',metrics:{intimacy:0},memories:[]}});

export const schedules = { speech:{name:'말 배우기',effects:{지능:3,사회성:1,집중력:1},fatigue:1,stress:0,hiddenTraitEffects:{leader:1,anxious:0.2}},storybook:{name:'그림책 보기',effects:{지능:1,감수성:3,호기심:2},fatigue:1,stress:-1,hiddenTraitEffects:{dreamer:1,creator:1,empathetic:1}},blocks:{name:'블록 쌓기',effects:{창의력:3,집중력:2},fatigue:1,stress:0,hiddenTraitEffects:{creator:2,obsessive:1}},walk:{name:'산책하기',effects:{체력:2,감수성:1,호기심:1},fatigue:1,stress:-2,hiddenTraitEffects:{explorer:2,stable:1}},nap:{name:'낮잠 자기',effects:{체력:2,자존감:1},fatigue:-3,stress:-2,hiddenTraitEffects:{stable:2}},toy:{name:'장난감 가지고 놀기',effects:{창의력:2,호기심:2,자존감:1},fatigue:1,stress:-1,hiddenTraitEffects:{dreamer:1,creator:1}},family:{name:'엄마 아빠와 시간 보내기',effects:{사회성:2,감수성:2,자존감:2},fatigue:0,stress:-2,hiddenTraitEffects:{empathetic:2,stable:1}},daydream:{name:'멍하니 상상하기',effects:{창의력:3,감수성:2},fatigue:-1,stress:-1,hiddenTraitEffects:{dreamer:2,creator:1,loner:1}}} as const;
const sceneBySeason: Record<ScheduleId, Record<SeasonLabel,string>>={walk:{봄:'동하는 젖은 흙냄새가 나는 길을 천천히 걸었다.',여름:'동하는 뜨거운 햇빛을 피해 그늘 쪽으로 걸었다.',가을:'동하는 낙엽이 밟히는 소리에 자꾸 고개를 돌렸다.',겨울:'동하는 차가운 공기에 잠시 눈을 깜빡였다.'},speech:{봄:'동하는 봄바람처럼 가벼운 소리를 흘렸다.',여름:'더운 낮, 동하는 짧은 소리를 반복했다.',가을:'조용한 오후, 동하는 작게 옹알거렸다.',겨울:'포근한 방 안에서 동하는 소리를 천천히 만들었다.'},storybook:{봄:'동하는 그림책 속 새싹 같은 색들을 오래 바라봤다.',여름:'긴 오후, 그림책은 그늘 같은 쉼이 됐다.',가을:'동하는 조용한 빛 속에서 한 페이지를 넘겼다.',겨울:'따뜻한 담요 아래에서 동하는 그림책을 꼭 잡았다.'},blocks:{봄:'동하는 블록으로 작은 놀이터를 만들었다.',여름:'천천히 식어가는 오후에 블록이 높아졌다.',가을:'바스락 소리 같은 리듬으로 블록을 올렸다.',겨울:'포근한 방 안에서 작은 세계를 쌓았다.'},nap:{봄:'봄빛이 흔들리는 사이 동하는 조용히 잠들었다.',여름:'더운 공기 속에서 동하는 길게 낮잠을 잤다.',가을:'조용한 오후, 동하는 깊게 숨을 고르며 잠들었다.',겨울:'따뜻한 이불 속에서 동하는 천천히 잠에 빠졌다.'},toy:{봄:'동하는 장난감을 들고 새로 만난 세상을 흉내 냈다.',여름:'긴 오후, 장난감 놀이는 끝날 줄 몰랐다.',가을:'동하는 장난감 소리에 귀를 기울이며 놀았다.',겨울:'포근한 방에서 동하는 작은 장난감을 꼭 쥐었다.'},family:{봄:'동하는 익숙한 품에서 봄처럼 느슨해졌다.',여름:'따뜻한 체온 속에서 동하는 편안히 기대었다.',가을:'조용한 저녁, 동하는 품 안에서 눈을 감았다.',겨울:'차가운 바깥과 달리 동하는 따뜻한 품을 오래 느꼈다.'},daydream:{봄:'창가에 앉은 동하는 봄빛을 바라보며 상상했다.',여름:'느린 오후, 동하는 멍하니 먼 곳을 봤다.',가을:'낙엽 소리를 들으며 동하는 생각에 잠겼다.',겨울:'포근한 실내에서 동하는 조용히 먼 이야기를 떠올렸다.'}};

export function createInitialState(): GameState { return { player:{name:'동하',age:1,season:0,week:1,money:0}, stats:{체력:30,지능:20,창의력:20,감수성:25,사회성:20,호기심:30,집중력:15,자존감:25}, fatigue:0,stress:0,actionsLeft:3,actionsPerWeek:3,flags:{introSeen:false},logs:[],memories:[],growthProfile:{hiddenTraits:mkTraits(),eventFlags:{metNeighborhoodChild:false,firstBugEncounter:false,metHeeseonAsChild:false},relationshipScores:{},endingSeeds:mkEndings()},relationships:mkRelationships(),relationshipEventFlags:{},seasonEventHistory:[],weeklyActivityHistory:[],recentConsecutiveActiveWeeks:0,weeklyReflections:[],emotionState:'calm',updatedAt:new Date().toISOString()}; }
export function getDateLabel(state:GameState){return `동하 ${state.player.age}살 · ${SEASONS[state.player.season]} · ${state.player.week}주차`;}
const addMemory=(s:GameState,seed:Omit<MemoryFragment,'age'|'season'|'week'>)=>{ const m={...seed,age:s.player.age,season:SEASONS[s.player.season],week:s.player.week}; s.memories=[...s.memories,m].slice(-120);};
const bumpRel=(s:GameState,key:string,metric:'intimacy'|'trust'|'curiosity'|'comfort',delta:number,title?:string)=>{const r=s.relationships[key]; if(!r)return; r.metrics[metric]=clamp((r.metrics[metric]??0)+delta); if(title) r.memories=[title,...r.memories].slice(0,5);};
const chance=(p:number)=>Math.random()<p;
function relationEvents(s:GameState,scheduleId:ScheduleId,lines:string[]){if(scheduleId==='family'){bumpRel(s,'parents','intimacy',3,'품 안에서 편안해진 날'); bumpRel(s,'parents','trust',2); s.growthProfile.hiddenTraits.stable+=1; s.stats.자존감=clamp(s.stats.자존감+2); addMemory(s,{id:`parents_${Date.now()}`,title:'품 안에서 편안해진 날',text:'동하는 익숙한 품 안에서 조금 더 편안해졌다. 세상이 아직은 안전한 곳이라고 느낀 것 같았다.',tags:['relationship','family','comfort','childhood'],emotionalTone:'warm',importance:3}); lines.push('관계 사건: 엄마 아빠와의 안정감이 깊어졌다.');}
if(scheduleId==='walk'||scheduleId==='toy'){if(chance(scheduleId==='toy'?0.25:0.18)){bumpRel(s,'neighborhoodChild','intimacy',1,'놀이터에서 마주친 날'); s.stats.사회성=clamp(s.stats.사회성+1); s.growthProfile.eventFlags.metNeighborhoodChild=true; addMemory(s,{id:`child_${Date.now()}`,title:'놀이터에서 마주친 아이',text:'놀이터 한쪽에서 또래 아이가 동하를 바라보았다. 동하는 잠시 눈을 마주쳤다가, 다시 장난감을 꼭 쥐었다.',tags:['relationship','childhood','friend'],emotionalTone:'quiet',importance:2}); lines.push('관계 사건: 동네 아이와 짧게 마주쳤다.');}}
if(scheduleId==='walk'&&chance(0.22)){bumpRel(s,'walkingGrandma','intimacy',1,'손을 흔들어 준 날'); s.growthProfile.hiddenTraits.empathetic+=1; s.growthProfile.hiddenTraits.stable+=1; addMemory(s,{id:`grandma_${Date.now()}`,title:'손을 흔들어 준 할머니',text:'산책길의 할머니가 동하에게 천천히 손을 흔들어 주었다. 동하는 조금 늦게, 아주 작게 손을 움직였다.',tags:['relationship','warm','childhood'],emotionalTone:'warm',importance:2}); lines.push('관계 사건: 산책길의 따뜻한 인사를 받았다.');}
if(scheduleId==='walk'&&chance(0.2)){bumpRel(s,'strangeDog','curiosity',2,'낯선 강아지를 바라본 날'); if(chance(0.7)) bumpRel(s,'strangeDog','comfort',1); else s.stress=clamp(s.stress+1); s.growthProfile.hiddenTraits.explorer+=1; addMemory(s,{id:`dog_${Date.now()}`,title:'낯선 강아지',text:'작은 강아지가 동하 가까이 다가왔다. 동하는 조금 겁먹은 듯했지만, 끝까지 눈을 떼지 않았다.',tags:['relationship','animal','childhood'],emotionalTone:'curious',importance:2});}
if(scheduleId==='walk'&&chance(0.24)){bumpRel(s,'tinyBug','curiosity',3,'작은 벌레와의 첫 만남'); s.stats.호기심=clamp(s.stats.호기심+2); s.growthProfile.hiddenTraits.explorer+=1; s.growthProfile.eventFlags.firstBugEncounter=true; addMemory(s,{id:`bug_${Date.now()}`,title:'작은 벌레와의 첫 만남',text:'작은 벌레 하나가 발밑을 지나갔다. 동하는 깜짝 놀랐지만, 그 작은 움직임을 오래 바라보았다.',tags:['relationship','nature','childhood','firstBugEncounter'],emotionalTone:'curious',importance:3});}
const season=SEASONS[s.player.season];
if(!s.growthProfile.eventFlags.metHeeseonAsChild&&s.player.age>=2&&(season==='봄'||season==='가을')&&(scheduleId==='walk'||scheduleId==='toy')&&chance(0.04)){s.growthProfile.eventFlags.metHeeseonAsChild=true; bumpRel(s,'heeseonSeed','intimacy',1,'또렷한 눈빛의 아이'); s.stats.감수성=clamp(s.stats.감수성+1); s.stats.호기심=clamp(s.stats.호기심+1); s.growthProfile.endingSeeds.belovedGameDirector+=0.5; s.growthProfile.endingSeeds.lateBloomingOrdinaryLife+=0.5; addMemory(s,{id:`heeseon_seed_${Date.now()}`,title:'또렷한 눈빛의 아이',text:'놀이터 저편에서 또렷한 눈빛의 아이가 잠시 동하를 바라보았다. 둘은 아무 말도 하지 않았다. 하지만 이상하게도, 그 짧은 순간은 오래 남을 것 같았다.',tags:['relationship','heeseonSeed','childhood','quiet'],emotionalTone:'quiet',importance:4}); lines.push('희미한 인연의 씨앗이 마음속에 남았다.');}}
function seasonalEvents(s:GameState,scheduleId:ScheduleId,lines:string[]){const season=SEASONS[s.player.season];
if(season==='봄'&&(scheduleId==='daydream'||scheduleId==='storybook')&&chance(0.22)){s.growthProfile.hiddenTraits.dreamer+=2;s.stats.감수성=clamp(s.stats.감수성+1);addMemory(s,{id:`rain_${Date.now()}`,title:'비 오는 창문',text:'창문 밖으로 아주 가는 비가 내렸다. 동하는 빗방울이 유리 위를 따라 내려가는 모습을 오래 바라보았다.',tags:['seasonal','spring','rain','quiet'],emotionalTone:'quiet',importance:2});lines.push('계절 사건: 봄비가 남긴 고요한 장면.');}
if(season==='여름'&&scheduleId==='nap'){s.fatigue=clamp(s.fatigue-10);s.stats.체력=clamp(s.stats.체력+2);s.growthProfile.hiddenTraits.stable+=1;addMemory(s,{id:`summer_nap_${Date.now()}`,title:'긴 낮잠',text:'여름의 긴 오후, 동하는 한참을 자고 일어났다. 세상은 조금 느리게 움직이는 것 같았다.',tags:['seasonal','summer','rest'],emotionalTone:'tired',importance:2});}
if(season==='가을'&&scheduleId==='walk'&&chance(0.26)){s.stats.감수성=clamp(s.stats.감수성+2);s.growthProfile.hiddenTraits.explorer+=1;addMemory(s,{id:`autumn_leaf_${Date.now()}`,title:'낙엽을 쥔 손',text:'동하는 작은 손에 낙엽 하나를 꼭 쥐었다. 바스락거리는 소리가 마음에 든 것 같았다.',tags:['seasonal','autumn','quiet','walk'],emotionalTone:'quiet',importance:2});}
if(season==='겨울'&&(scheduleId==='blocks'||scheduleId==='toy')){s.growthProfile.hiddenTraits.creator+=1;s.growthProfile.hiddenTraits.stable+=1;addMemory(s,{id:`winter_blocks_${Date.now()}`,title:'따뜻한 방의 블록',text:'차가운 바깥과 달리 방 안은 포근했다. 동하는 블록을 하나씩 쌓으며 자기만의 작은 세계를 만들었다.',tags:['seasonal','winter','family-comfort'],emotionalTone:'warm',importance:2});}
}
export function resolveEmotionState(state:GameState):EmotionState{if(state.stats.체력<=50)return'sick';if(state.fatigue>=75)return'tired';if(state.stress>=70)return'stressed';if(state.stats.자존감>=20&&state.stress<40)return'happy';if(state.stats.호기심>=15)return'curious';if(state.growthProfile.hiddenTraits.dreamer>=10)return'dreaming';return'calm';}
export function updateEndingSeeds(s:GameState){const t=s.growthProfile.hiddenTraits;const m=s.memories; if((s.relationships.parents.metrics.trust??0)>=12&&t.stable>=8){s.growthProfile.endingSeeds.warmTeacher+=1;s.growthProfile.endingSeeds.lateBloomingOrdinaryLife+=0.7;} if((s.relationships.neighborhoodChild.metrics.intimacy??0)>=5&&s.stats.사회성>=35){s.growthProfile.endingSeeds.belovedGameDirector+=1;} if(((s.relationships.tinyBug.metrics.curiosity??0)+(s.relationships.strangeDog.metrics.curiosity??0)>=8)){s.growthProfile.endingSeeds.natureDocumentaryMaker+=1;} if(s.growthProfile.eventFlags.metHeeseonAsChild){s.growthProfile.eventFlags.heeseonRouteUnlocked=true;} const quietCount=m.filter(v=>v.tags.includes('rain')||v.tags.includes('autumn')||v.tags.includes('quiet')).length; if(quietCount>=4){s.growthProfile.endingSeeds.quietNovelist+=1;s.growthProfile.endingSeeds.indieGameCreator+=0.5;}}
export function getEndingCandidates(state:GameState){return Object.entries(state.growthProfile.endingSeeds).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([id,score])=>({id,score:Number(score.toFixed(1))}));}
export function getWeeklyReflection(state:GameState){return state.memories[state.memories.length-1]?.text ?? '동하는 천천히, 자기만의 속도로 한 주를 건넜다.';}
export function applyActivity(state:GameState,scheduleId:ScheduleId){ if(state.actionsLeft<=0)return{state,summary:'이번 주 행동을 모두 사용했습니다.',resultLines:['이번 주를 마무리해 주세요.'],scheduleName:'행동 불가'}; const next=structuredClone(state); const lines:string[]=[]; const selected=schedules[scheduleId] as any; Object.entries(selected.effects).forEach(([k,v])=>{next.stats[k as StatName]=clamp(next.stats[k as StatName]+Number(v)); lines.push(`${k} +${v}`);}); next.fatigue=clamp(next.fatigue+selected.fatigue); next.stress=clamp(next.stress+selected.stress); next.actionsLeft-=1; next.weeklyActivityHistory.push(scheduleId); Object.entries(selected.hiddenTraitEffects??{}).forEach(([k,v])=>next.growthProfile.hiddenTraits[k as HiddenTraitName]+=Number(v)); if(scheduleId==='daydream'&&next.weeklyActivityHistory.filter(v=>v==='daydream').length>=3) next.growthProfile.hiddenTraits.loner+=1; relationEvents(next,scheduleId,lines); seasonalEvents(next,scheduleId,lines); updateEndingSeeds(next); const weekLabel=getDateLabel(next); next.logs=[{weekLabel,scheduleName:schedules[scheduleId].name,lines},...next.logs].slice(0,24); next.emotionState=resolveEmotionState(next); next.updatedAt=new Date().toISOString(); return {state:next,summary:getWeeklyReflection(next),resultLines:lines,scheduleName:schedules[scheduleId].name,resultSceneText:sceneBySeason[scheduleId][SEASONS[next.player.season]],newMemories:next.memories.slice(-2)}; }
export function endWeek(state:GameState){const next=structuredClone(state); next.weeklyReflections=[getWeeklyReflection(next),...next.weeklyReflections].slice(0,12); return advanceTime(next);} 
export function advanceTime(state:GameState){const next=structuredClone(state); const prevSeason=next.player.season; if(next.player.week>=4){next.player.week=1; next.player.season=next.player.season>=3?0:next.player.season+1; if(next.player.season===0) next.player.age+=1;} else next.player.week+=1; if(next.player.season!==prevSeason){next.seasonEventHistory=[...next.seasonEventHistory,`season_${SEASONS[next.player.season]}_${next.player.age}_${next.player.week}`].slice(-80);} next.actionsLeft=next.actionsPerWeek; next.fatigue=Math.max(0,next.fatigue-2); next.stress=Math.max(0,next.stress-1); next.weeklyActivityHistory=[]; next.updatedAt=new Date().toISOString(); return next;}
export const runWeek=applyActivity; export const advanceWeek=endWeek;
